<?php

/* 
 * Copyright (C) 2014 Pedro Gabriel Manrique Gutiérrez <pedrogmanrique at gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<p><?php  if(isset($this->valorGuardar)) echo $this->valorGuardar;?></p>
<form id="form1" action="<?php echo BASE_URL; ?>post/nuevo" method="post">
    <input type="hidden" name ="guardar" value="1">
    
    <label for="titulo">Título</label><br />
    <input type="text" name="titulo" 
           value="<?php if(!empty($this->datos['titulo']))echo $this->datos['titulo'];?>">
    <br />
    <label for="cuerpo">Cuerpo</label><br />
    <textarea name="cuerpo">
        <?php if(!empty($this->datos['cuerpo']))echo $this->datos['cuerpo'];?>
    </textarea><br />
    <input type="submit" value="Guardar" class="btn long">
</form>

